### ISSUE TITLE
Styling Enhancements (see checklist below)

### ISSUE THREAD

**Issue by ColemanMitch** [wkhori-wmp/nhbc-2022#25]
Don't have to knock out all of these in one PR, but indicate whichever ones you do end up tackling

- [x]  Add radius to form input boxes 
- [x]  Style `Export to .csv` link 
- [ ]  Add background color to pages 
- [ ]  Style page headers
