### ISSUE TITLE
TO DOS README

### ISSUE THREAD

**Issue by ColemanMitch** [wkhori-wmp/nhbc-2022#39]
### Please read!! branch naming convention below 👇!!! 
---
`nhbc-2022/todo/{some semantic name that's not too long}`

e.g. `nhbc-2022/todo/root-id`, `nhbc-2022/todo/embed-gif`

---

**HTML**

- [x] Have the new hires delete the id="root" from the app to see what happens to the app #40 
- [x] Have the new hires embed the .gif #41 

 
**CSS** 

- [x] Break the CSS for a page and have them change the style of a few styled components #42 

 
 
**React** 

- [x] array.map() #43 
- [x] Conditionally rendering #44 
- [x] onSubmit or onChange for form (explain how the payload is sent to BE) #45 

 Hooks
- [x] useState #46 
- State management (add song refresh bug)
- [x] useEffect #47 
- [x] useHistory #48 
- useParams(?)
- Have them add a route back in (react router)
- Put the route into the navbar
